<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1. Fuentes de datos: búsqueda, catálogo e integración – Proyecto Integrador - Almacenes y Minería de Datos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../entregas/E1_arquitectura_dw/arquitectura.html" rel="next">
<link href="../../entregas/E0_comprension_negocio/fuentes.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-386f47455dee9819add0e62fdb7410f3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Proyecto Integrador - Almacenes y Minería de Datos</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-e0---comprensión-del-negocio" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">E0 - Comprensión del Negocio</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-e0---comprensión-del-negocio">    
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/bitacora.html">
 <span class="dropdown-text">1. Bitácora del stakeholder</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/canvas.html">
 <span class="dropdown-text">2. Business Understanding Canvas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/preguntas.html">
 <span class="dropdown-text">3. Preguntas de investigación</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/criterio_exito.html">
 <span class="dropdown-text">4. Criterio de éxito</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/riesgos_supuestos.html">
 <span class="dropdown-text">5. Supuestos y riesgos</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/uso_ia.html">
 <span class="dropdown-text">6. Uso de herramientas de IA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E0_comprension_negocio/fuentes.html">
 <span class="dropdown-text">7. Fuentes consultadas</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-e1---arquitectura-del-dw" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">E1 - Arquitectura del DW</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-e1---arquitectura-del-dw">    
        <li>
    <a class="dropdown-item" href="../../entregas/E1_arquitectura_dw/fuentes.html">
 <span class="dropdown-text">1. Fuentes de datos</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E1_arquitectura_dw/arquitectura.html">
 <span class="dropdown-text">2. Arquitectura de tres capas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E1_arquitectura_dw/estrella.html">
 <span class="dropdown-text">3. Esquema estrella</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../entregas/E1_arquitectura_dw/trazabilidad.html">
 <span class="dropdown-text">4. Matriz de trazabilidad</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../entregas/E1_arquitectura_dw/uso_ia.html">
 <span class="dropdown-text">5. Uso de herramientas de IA</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../entregas/E1_arquitectura_dw/fuentes.html">E1 - Arquitectura del DW</a></li><li class="breadcrumb-item"><a href="../../entregas/E1_arquitectura_dw/fuentes.html">1. Fuentes de datos: búsqueda, catálogo e integración</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inicio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">E0 - Comprensión del Negocio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/bitacora.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Bitácora de la reunión con el stakeholder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/canvas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Business Understanding Canvas (CRISP-DM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/preguntas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Preguntas de investigación priorizadas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/criterio_exito.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Criterio de éxito en términos de negocio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/riesgos_supuestos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Supuestos y riesgos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/uso_ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Documentación del uso de herramientas de IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E0_comprension_negocio/fuentes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Fuentes consultadas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">E1 - Arquitectura del DW</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E1_arquitectura_dw/fuentes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">1. Fuentes de datos: búsqueda, catálogo e integración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E1_arquitectura_dw/arquitectura.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Arquitectura de tres capas en BigQuery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E1_arquitectura_dw/estrella.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Esquema estrella</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E1_arquitectura_dw/trazabilidad.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Matriz de trazabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../entregas/E1_arquitectura_dw/uso_ia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Documentación del uso de herramientas de IA</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#punto-de-partida-preguntas-de-e0" id="toc-punto-de-partida-preguntas-de-e0" class="nav-link active" data-scroll-target="#punto-de-partida-preguntas-de-e0">Punto de partida: preguntas de E0</a></li>
  <li><a href="#proceso-de-búsqueda" id="toc-proceso-de-búsqueda" class="nav-link" data-scroll-target="#proceso-de-búsqueda">1.1 Proceso de búsqueda</a></li>
  <li><a href="#candidatas-evaluadas-y-criterio-de-selección" id="toc-candidatas-evaluadas-y-criterio-de-selección" class="nav-link" data-scroll-target="#candidatas-evaluadas-y-criterio-de-selección">1.2 Candidatas evaluadas y criterio de selección</a></li>
  <li><a href="#catálogo-de-fuentes-verificadas" id="toc-catálogo-de-fuentes-verificadas" class="nav-link" data-scroll-target="#catálogo-de-fuentes-verificadas">1.3 Catálogo de fuentes verificadas</a>
  <ul class="collapse">
  <li><a href="#f1" id="toc-f1" class="nav-link" data-scroll-target="#f1">F1 · Afluencia diaria del Metro CDMX (simple)</a></li>
  <li><a href="#f2" id="toc-f2" class="nav-link" data-scroll-target="#f2">F2 · Afluencia diaria del Metrobús CDMX (simple)</a></li>
  <li><a href="#f3" id="toc-f3" class="nav-link" data-scroll-target="#f3">F3 · GTFS estático de la Ciudad de México</a></li>
  <li><a href="#f4" id="toc-f4" class="nav-link" data-scroll-target="#f4">F4 · Días festivos de México (Nager.Date)</a></li>
  <li><a href="#f5" id="toc-f5" class="nav-link" data-scroll-target="#f5">F5 · Clima histórico diario (Open-Meteo)</a></li>
  </ul></li>
  <li><a href="#lo-que-encontramos-al-abrir-los-datos" id="toc-lo-que-encontramos-al-abrir-los-datos" class="nav-link" data-scroll-target="#lo-que-encontramos-al-abrir-los-datos">1.4 Lo que encontramos al abrir los datos</a>
  <ul class="collapse">
  <li><a href="#verificación-en-bigquery" id="toc-verificación-en-bigquery" class="nav-link" data-scroll-target="#verificación-en-bigquery">Verificación en BigQuery</a></li>
  </ul></li>
  <li><a href="#análisis-de-integración" id="toc-análisis-de-integración" class="nav-link" data-scroll-target="#análisis-de-integración">1.5 Análisis de integración</a>
  <ul class="collapse">
  <li><a href="#llaves-de-unión" id="toc-llaves-de-unión" class="nav-link" data-scroll-target="#llaves-de-unión">Llaves de unión</a></li>
  <li><a href="#diferencias-de-granularidad" id="toc-diferencias-de-granularidad" class="nav-link" data-scroll-target="#diferencias-de-granularidad">Diferencias de granularidad</a></li>
  <li><a href="#problemas-anticipados-se-documentan-se-resuelven-en-e2" id="toc-problemas-anticipados-se-documentan-se-resuelven-en-e2" class="nav-link" data-scroll-target="#problemas-anticipados-se-documentan-se-resuelven-en-e2">Problemas anticipados (se documentan, se resuelven en E2)</a></li>
  </ul></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../entregas/E1_arquitectura_dw/fuentes.html">E1 - Arquitectura del DW</a></li><li class="breadcrumb-item"><a href="../../entregas/E1_arquitectura_dw/fuentes.html">1. Fuentes de datos: búsqueda, catálogo e integración</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">1. Fuentes de datos: búsqueda, catálogo e integración</h1>
<p class="subtitle lead">Entrega E1 - Arquitectura del Data Warehouse</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="punto-de-partida-preguntas-de-e0" class="level2">
<h2 class="anchored" data-anchor-id="punto-de-partida-preguntas-de-e0">Punto de partida: preguntas de E0</h2>
<p>Las preguntas priorizadas en E0 reciben un identificador que se usa en toda la entrega.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 42%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>ID</th>
<th>Pregunta de E0</th>
<th>Tarea de minería</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>P1</strong></td>
<td>¿Qué combinaciones de línea, estación y día de la semana concentran los picos de afluencia, y qué tan lejos están de su nivel base?</td>
<td>EDA / estacionalidad</td>
</tr>
<tr class="even">
<td><strong>P2</strong></td>
<td>¿Es posible anticipar con al menos 24 h la afluencia diaria por estación y clasificar los días de alta demanda?</td>
<td>Regresión + clasificación</td>
</tr>
<tr class="odd">
<td><strong>P3</strong></td>
<td>¿Cuántos perfiles de demanda existen entre las estaciones y qué alternativas (Metro o Metrobús) hay para cada perfil?</td>
<td>Clustering</td>
</tr>
<tr class="even">
<td><strong>P4</strong></td>
<td>¿Qué días son anomalías y qué proporción se explica por eventos identificables?</td>
<td>Detección de anomalías</td>
</tr>
<tr class="odd">
<td><strong>P5</strong> <em>(reserva)</em></td>
<td>¿El Metrobús absorbe demanda cuando una línea del Metro suspende servicio?</td>
<td>Correlación / cambio de nivel</td>
</tr>
</tbody>
</table>
</section>
<section id="proceso-de-búsqueda" class="level2">
<h2 class="anchored" data-anchor-id="proceso-de-búsqueda">1.1 Proceso de búsqueda</h2>
<p>La búsqueda combinó una herramienta de investigación con IA (documentada en <a href="../../entregas/E1_arquitectura_dw/uso_ia.html">Uso de IA</a>) con consultas directas a los portales. Todo lo que propuso la herramienta se abrió y se comprobó en la fuente original antes de entrar al catálogo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 44%">
<col style="width: 20%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th>Fecha</th>
<th>Herramienta o portal</th>
<th>Consulta</th>
<th>Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-10-01</td>
<td>API CKAN del Portal de Datos Abiertos CDMX (<code>package_search</code>)</td>
<td><code>afluencia metrobus</code>, <code>estaciones metro</code>, <code>gtfs</code></td>
<td>6 conjuntos de SEMOVI relevantes (C1–C6, C12)</td>
</tr>
<tr class="even">
<td>2026-10-01</td>
<td>API CKAN (<code>datastore_search_sql</code>)</td>
<td>Perfilado de F1 y F2: rango de fechas, filas por día, valores distintos de línea y estación, ceros</td>
<td>Hallazgos de la sección 1.4</td>
</tr>
<tr class="odd">
<td>2026-10-01</td>
<td>Búsqueda web</td>
<td><code>INEGI Estadística de Transporte Urbano de Pasajeros mensual Metro</code></td>
<td>ETUP de INEGI (C9)</td>
</tr>
<tr class="even">
<td>2026-10-01</td>
<td>Nager.Date (API REST)</td>
<td><code>/api/v3/PublicHolidays/{año}/MX</code>, 2010–2026</td>
<td>156 registros de festivos (F4)</td>
</tr>
<tr class="odd">
<td>2026-10-01</td>
<td>Open-Meteo Historical Weather API</td>
<td>Precipitación y temperatura diaria, CDMX, 2010–2026</td>
<td>6,056 días sin huecos (F5)</td>
</tr>
<tr class="even">
<td>2026-10-01</td>
<td>Catálogo <code>bigquery-public-data</code></td>
<td>Clima diario con estaciones en México</td>
<td>NOAA GSOD (C10), no incorporado</td>
</tr>
<tr class="odd">
<td>2026-10-01</td>
<td>Documentación de Waze for Cities</td>
<td>Acceso a datos de tráfico</td>
<td>Sin API pública (C11), descartado desde E0</td>
</tr>
</tbody>
</table>
</section>
<section id="candidatas-evaluadas-y-criterio-de-selección" class="level2">
<h2 class="anchored" data-anchor-id="candidatas-evaluadas-y-criterio-de-selección">1.2 Candidatas evaluadas y criterio de selección</h2>
<p>Una fuente entra al catálogo solo si cumple los seis criterios:</p>
<ol type="1">
<li><strong>Grano compatible:</strong> diario, y por estación o por línea.</li>
<li><strong>Cobertura:</strong> incluye 2022–2026, que es la ventana del modelo operativo definida en E0 (riesgo R5).</li>
<li><strong>Licencia abierta</strong> que permita el uso y la redistribución académica.</li>
<li><strong>Acceso reproducible</strong> sin credenciales: descarga directa o API sin llave.</li>
<li><strong>Llave de integración</strong> con las demás fuentes (fecha, línea o estación).</li>
<li><strong>Responde al menos una pregunta</strong> P1–P5.</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 24%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Candidata</th>
<th>Dueño</th>
<th>Tipo</th>
<th>Decisión</th>
<th>Motivo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C1</td>
<td>Afluencia diaria del Metro (simple)</td>
<td>SEMOVI</td>
<td>CSV en portal</td>
<td>✅ <strong>F1</strong></td>
<td>Única fuente con grano estación-día; núcleo del DW</td>
</tr>
<tr class="even">
<td>C2</td>
<td>Afluencia diaria del Metrobús (simple)</td>
<td>SEMOVI</td>
<td>CSV en portal</td>
<td>✅ <strong>F2</strong></td>
<td>Único dato de demanda del modo alterno (P3, P5)</td>
</tr>
<tr class="odd">
<td>C3</td>
<td>GTFS estático de la CDMX</td>
<td>SEMOVI</td>
<td>ZIP de CSV (estándar GTFS)</td>
<td>✅ <strong>F3</strong></td>
<td>Catálogo canónico de estaciones y líneas con identificador y coordenadas</td>
</tr>
<tr class="even">
<td>C4</td>
<td>Días festivos de México (Nager.Date)</td>
<td>Proyecto Nager.Date</td>
<td>API REST JSON</td>
<td>✅ <strong>F4</strong></td>
<td>Festivos para <code>dim_fecha</code> (P1, P2, P4)</td>
</tr>
<tr class="odd">
<td>C5</td>
<td>Clima histórico diario (Open-Meteo)</td>
<td>Open-Meteo</td>
<td>API REST CSV/JSON</td>
<td>✅ <strong>F5</strong></td>
<td>Lluvia y temperatura para explicar anomalías (P4) y como variable de P2</td>
</tr>
<tr class="even">
<td>C6</td>
<td>Afluencia diaria del Metro (desglosada por tipo de pago)</td>
<td>SEMOVI</td>
<td>CSV en portal</td>
<td>❌</td>
<td>Mismo grano que F1 más <code>tipo_pago</code>, pero solo desde 2021 y ninguna pregunta usa el medio de pago: crearía una dimensión huérfana</td>
</tr>
<tr class="odd">
<td>C7</td>
<td>Afluencia preliminar en transporte público</td>
<td>SEMOVI</td>
<td>CSV en portal</td>
<td>❌</td>
<td>Cifras preliminares, agregadas por organismo, con números como texto (<code>"11,238"</code>) y solo desde 2020-03; redundante con F1 y F2</td>
</tr>
<tr class="even">
<td>C8</td>
<td>Datos de movilidad (histórico COVID-19)</td>
<td>SEMOVI</td>
<td>CSV en portal</td>
<td>❌</td>
<td>Índices relativos, no conteos, y solo para el periodo de pandemia</td>
</tr>
<tr class="odd">
<td>C9</td>
<td>Estadística de Transporte Urbano de Pasajeros (ETUP)</td>
<td>INEGI</td>
<td>Tabulados / PDF mensual</td>
<td>❌</td>
<td>Grano mensual por sistema, no por estación; útil en E2 solo para validar totales</td>
</tr>
<tr class="even">
<td>C10</td>
<td>NOAA GSOD (<code>bigquery-public-data.noaa_gsod</code>)</td>
<td>NOAA</td>
<td>Dataset público de BigQuery</td>
<td>❌</td>
<td>Duplica la necesidad que cubre F5 y su consulta consume créditos; no se verificó la cobertura de la estación de la CDMX</td>
</tr>
<tr class="odd">
<td>C11</td>
<td>Waze for Cities</td>
<td>Google / Waze</td>
<td>Feed para socios</td>
<td>❌</td>
<td>Sin API pública y con prohibición de republicar (riesgo R7 de E0)</td>
</tr>
<tr class="even">
<td>C12</td>
<td>Ubicación de líneas y estaciones del Metro</td>
<td>SEMOVI</td>
<td>SHP / KMZ</td>
<td>❌</td>
<td>Mismo contenido geográfico que F3, pero en un formato que BigQuery no carga directamente y sin identificador de parada</td>
</tr>
</tbody>
</table>
<p>El catálogo cumple el requisito de <strong>dos tipos distintos</strong>: archivos de portal abierto (F1, F2, F3) y API REST (F4, F5).</p>
</section>
<section id="catálogo-de-fuentes-verificadas" class="level2">
<h2 class="anchored" data-anchor-id="catálogo-de-fuentes-verificadas">1.3 Catálogo de fuentes verificadas</h2>
<section id="f1" class="level3">
<h3 class="anchored" data-anchor-id="f1">F1 · Afluencia diaria del Metro CDMX (simple)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Nombre y dueño</strong></td>
<td>Afluencia Diaria del Metro (Simple) · Secretaría de Movilidad (SEMOVI)</td>
</tr>
<tr class="even">
<td><strong>URL y acceso</strong></td>
<td><a href="https://datos.cdmx.gob.mx/dataset/afluencia-diaria-del-metro-cdmx" class="uri">https://datos.cdmx.gob.mx/dataset/afluencia-diaria-del-metro-cdmx</a> · descarga directa de CSV; también por API CKAN (<code>resource_id 0e8ffe58-28bb-4dde-afcd-e5f5b4de4ccb</code>)</td>
</tr>
<tr class="odd">
<td><strong>Formato y tamaño</strong></td>
<td>CSV, 59.9 MB, 1,180,920 filas; columnas <code>fecha, anio, mes, linea, estacion, afluencia</code></td>
</tr>
<tr class="even">
<td><strong>Grano</strong></td>
<td>Una fila por estación-línea por día (195 filas exactas cada día)</td>
</tr>
<tr class="odd">
<td><strong>Cobertura</strong></td>
<td>2010-01-01 a 2026-07-31 (6,056 días); 12 líneas, 195 estaciones-línea; actualización mensual (última: 2026-08-28)</td>
</tr>
<tr class="even">
<td><strong>Licencia y restricciones</strong></td>
<td>CC-BY-4.0-ESP, con atribución. Sin datos personales. El portal advierte actualizaciones retroactivas</td>
</tr>
<tr class="odd">
<td><strong>Llaves de integración</strong></td>
<td><code>fecha</code> (ISO); <code>linea</code> + <code>estacion</code> (texto, requiere normalización)</td>
</tr>
<tr class="even">
<td><strong>Pregunta(s) de E0</strong></td>
<td>P1, P2, P3, P4, P5</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/F1_portal.jpeg" class="img-fluid figure-img"></p>
<figcaption>Página del conjunto en el portal</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/STG_preview_metro.png" class="img-fluid figure-img"></p>
<figcaption>Vista previa en staging (BigQuery)</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="f2" class="level3">
<h3 class="anchored" data-anchor-id="f2">F2 · Afluencia diaria del Metrobús CDMX (simple)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Nombre y dueño</strong></td>
<td>Afluencia Diaria del Metrobús (Simple) · SEMOVI</td>
</tr>
<tr class="even">
<td><strong>URL y acceso</strong></td>
<td><a href="https://datos.cdmx.gob.mx/dataset/afluencia-diaria-de-metrobus-cdmx" class="uri">https://datos.cdmx.gob.mx/dataset/afluencia-diaria-de-metrobus-cdmx</a> · descarga directa de CSV; API CKAN (<code>resource_id f7943c47-835d-4078-93ea-906f64b72f3b</code>)</td>
</tr>
<tr class="odd">
<td><strong>Formato y tamaño</strong></td>
<td>CSV, 2.1 MB, 53,732 filas; columnas <code>fecha, anio, mes, linea, afluencia</code></td>
</tr>
<tr class="even">
<td><strong>Grano</strong></td>
<td>Una fila por línea de Metrobús por día. <strong>No hay detalle por estación</strong></td>
</tr>
<tr class="odd">
<td><strong>Cobertura</strong></td>
<td>2005-07-26 a 2026-07-31; 7 líneas; actualización mensual</td>
</tr>
<tr class="even">
<td><strong>Licencia y restricciones</strong></td>
<td>CC-BY-4.0-ESP. Sin datos personales</td>
</tr>
<tr class="odd">
<td><strong>Llaves de integración</strong></td>
<td><code>fecha</code>; <code>linea</code> (texto, con variantes de mayúsculas)</td>
</tr>
<tr class="even">
<td><strong>Pregunta(s) de E0</strong></td>
<td>P3, P5</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/F2_portal.jpeg" class="img-fluid figure-img"></p>
<figcaption>Página del conjunto en el portal</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/STG_preview_metrobus.png" class="img-fluid figure-img"></p>
<figcaption>Vista previa en staging (BigQuery)</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="f3" class="level3">
<h3 class="anchored" data-anchor-id="f3">F3 · GTFS estático de la Ciudad de México</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Nombre y dueño</strong></td>
<td>GTFS estático (General Transit Feed Specification) de la Ciudad de México · SEMOVI</td>
</tr>
<tr class="even">
<td><strong>URL y acceso</strong></td>
<td><a href="https://datos.cdmx.gob.mx/dataset/gtfs" class="uri">https://datos.cdmx.gob.mx/dataset/gtfs</a> · descarga directa de ZIP; se cargan <code>stops.txt</code> y <code>routes.txt</code></td>
</tr>
<tr class="odd">
<td><strong>Formato y tamaño</strong></td>
<td>ZIP de 2.4 MB con 8 archivos CSV; <code>stops.txt</code> 1.0 MB (11,362 paradas de todos los sistemas), <code>routes.txt</code> 21.6 KB</td>
</tr>
<tr class="even">
<td><strong>Grano</strong></td>
<td><code>stops.txt</code>: una fila por parada. El Metro (agencia <code>METRO</code>, prefijo <code>B_02</code>) tiene <strong>195 paradas</strong>, una por estación-línea. <code>routes.txt</code>: una fila por ruta</td>
</tr>
<tr class="odd">
<td><strong>Cobertura</strong></td>
<td>Foto de la red al <strong>31 de octubre de 2022</strong>, según la descripción del conjunto (el portal registra una modificación de metadatos el 2026-08-28, pero el contenido no cambió de versión). Es un catálogo estático, sin historia; incluye Metro, Metrobús y otros 8 sistemas</td>
</tr>
<tr class="even">
<td><strong>Licencia y restricciones</strong></td>
<td>CC-BY-4.0-ESP. Sin datos personales</td>
</tr>
<tr class="odd">
<td><strong>Llaves de integración</strong></td>
<td><code>stop_id</code> (p.&nbsp;ej. <code>B_0200L1-PANTITLAN</code> contiene la línea); <code>stop_name</code>; <code>route_short_name</code> (<code>1</code>…<code>9</code>, <code>A</code>, <code>B</code>, <code>L12</code>); coordenadas</td>
</tr>
<tr class="even">
<td><strong>Pregunta(s) de E0</strong></td>
<td>P1, P3, P4 (catálogo de estaciones y líneas)</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/F3_portal.jpeg" class="img-fluid figure-img"></p>
<figcaption>Página del conjunto en el portal</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/STG_preview_gtfs_stops.png" class="img-fluid figure-img"></p>
<figcaption>Vista previa de stops.txt en staging</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="f4" class="level3">
<h3 class="anchored" data-anchor-id="f4">F4 · Días festivos de México (Nager.Date)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Nombre y dueño</strong></td>
<td>Public Holidays API · proyecto Nager.Date (código abierto, licencia MIT)</td>
</tr>
<tr class="even">
<td><strong>URL y acceso</strong></td>
<td><a href="https://date.nager.at/api/v3/PublicHolidays/2025/MX" class="uri">https://date.nager.at/api/v3/PublicHolidays/2025/MX</a> · API REST sin llave, una llamada por año</td>
</tr>
<tr class="odd">
<td><strong>Formato y tamaño</strong></td>
<td>JSON; 156 registros para 2010–2026 (≈ 29 KB); campos <code>date, localName, name, global, types</code></td>
</tr>
<tr class="even">
<td><strong>Grano</strong></td>
<td>Una fila por día festivo</td>
</tr>
<tr class="odd">
<td><strong>Cobertura</strong></td>
<td>Cualquier año; México a nivel nacional</td>
</tr>
<tr class="even">
<td><strong>Licencia y restricciones</strong></td>
<td>Uso libre de la API. Incluye días que <strong>no</strong> son de descanso obligatorio (Jueves y Viernes Santo con tipo <code>Bank</code>/<code>School</code>) y algunos festivos desplazados que no corresponden a la ley (ver 1.5)</td>
</tr>
<tr class="odd">
<td><strong>Llaves de integración</strong></td>
<td><code>date</code> (ISO)</td>
</tr>
<tr class="even">
<td><strong>Pregunta(s) de E0</strong></td>
<td>P1, P2, P4</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/F4_api.jpeg" class="img-fluid figure-img"></p>
<figcaption>Respuesta de la API en el navegador</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/STG_preview_festivos.png" class="img-fluid figure-img"></p>
<figcaption>Vista previa en staging</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="f5" class="level3">
<h3 class="anchored" data-anchor-id="f5">F5 · Clima histórico diario (Open-Meteo)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Nombre y dueño</strong></td>
<td>Historical Weather API · Open-Meteo</td>
</tr>
<tr class="even">
<td><strong>URL y acceso</strong></td>
<td><a href="https://archive-api.open-meteo.com/v1/archive" class="uri">https://archive-api.open-meteo.com/v1/archive</a> · API REST sin llave; parámetros <code>latitude=19.4326&amp;longitude=-99.1332&amp;daily=precipitation_sum,rain_sum,temperature_2m_max,temperature_2m_min&amp;timezone=America/Mexico_City&amp;format=csv</code></td>
</tr>
<tr class="odd">
<td><strong>Formato y tamaño</strong></td>
<td>CSV, 187 KB, 6,056 filas para 2010-01-01 → 2026-07-31; 4 líneas iniciales de metadatos</td>
</tr>
<tr class="even">
<td><strong>Grano</strong></td>
<td>Una fila por día para un punto de malla (19.4376 N, −99.1072 O, 2,230 m)</td>
</tr>
<tr class="odd">
<td><strong>Cobertura</strong></td>
<td>Desde 1940 hasta hace pocos días; reanálisis, por lo que valores recientes pueden revisarse</td>
</tr>
<tr class="even">
<td><strong>Licencia y restricciones</strong></td>
<td>CC BY 4.0, con atribución a Open-Meteo</td>
</tr>
<tr class="odd">
<td><strong>Llaves de integración</strong></td>
<td><code>time</code> (fecha ISO en hora local de la CDMX)</td>
</tr>
<tr class="even">
<td><strong>Pregunta(s) de E0</strong></td>
<td>P2, P4</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/F5_api.jpeg" class="img-fluid figure-img"></p>
<figcaption>Respuesta de la API en el navegador</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/STG_preview_clima.png" class="img-fluid figure-img"></p>
<figcaption>Vista previa en staging</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="lo-que-encontramos-al-abrir-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="lo-que-encontramos-al-abrir-los-datos">1.4 Lo que encontramos al abrir los datos</h2>
<p>Antes de diseñar el esquema perfilamos F1 y F2 completas con la API del portal. La consulta para repetir cada hallazgo en BigQuery está en <a href="sql/01_perfilado_staging.sql"><code>sql/01_perfilado_staging.sql</code></a>.</p>
<ul>
<li><strong>F1 es un panel completo:</strong> exactamente <strong>195 filas por día</strong> durante los 6,056 días. No faltan estación-días: lo que hay son <strong>ceros</strong>.</li>
<li><strong>62,025 registros en cero (5.3 %)</strong>, casi todos estructurales:
<ul>
<li>Línea 12 antes de su inauguración: primer valor distinto de cero el 2012-11-05.</li>
<li>Línea 12 cerrada desde el 2021-05-04, día siguiente al colapso, con reapertura escalonada en 2023 y enero de 2024.</li>
<li>Línea 1 durante la modernización de 2022–2025, el riesgo R3 de E0.</li>
</ul></li>
<li><strong>Codificación inconsistente:</strong> entre 2021-01-01 y 2023-05-31 el campo <code>linea</code> cambia de <code>Linea 1</code> a <code>LÃ­nea 1</code>. Es texto UTF-8 leído como Latin-1. Por eso hay <strong>24 valores de línea para 12 líneas</strong>. Lo mismo ocurre en nombres de estación (<code>PantitlÃ¡n</code>, <code>GÃ³mez FarÃ­as</code>), incluso fuera de ese periodo. El riesgo R6 de E0 se <strong>confirmó</strong>.</li>
<li><strong>F2 marca con el texto <code>'NaN'</code></strong> las fechas en que una línea aún no existía: 17,227 filas. En 2023 los nombres aparecen en minúsculas (<code>linea 1</code>).</li>
</ul>
<section id="verificación-en-bigquery" class="level3">
<h3 class="anchored" data-anchor-id="verificación-en-bigquery">Verificación en BigQuery</h3>
<p>Después de cargar staging, el equipo repitió el perfilado en BigQuery con <a href="sql/01_perfilado_staging.sql"><code>sql/01_perfilado_staging.sql</code></a>. Las 8 consultas se ejecutaron sin error y cada cifra coincide con la que obtuvimos en el portal.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_resumen.png" class="img-fluid figure-img"></p>
<figcaption>Ejecución de las 8 consultas de perfilado</figcaption>
</figure>
</div>
<div class="quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f1_cobertura.png" class="img-fluid figure-img"></p>
<figcaption>F1 · cobertura: 2010-01-01 a 2026-07-31, 1,180,920 filas, 6,056 días</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/STG_perfilado.png" class="img-fluid figure-img"></p>
<figcaption>F1 · panel completo: 195 filas en cada uno de los 6,056 días</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f1_lineas_codificacion.png" class="img-fluid figure-img"></p>
<figcaption>F1 · 24 valores de <code>linea</code> para 12 líneas: <code>Linea</code> y <code>LÃ­nea</code> (2021-01-01 a 2023-05-31)</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f1_ceros.png" class="img-fluid figure-img"></p>
<figcaption>F1 · ceros por línea y año: L12 antes de 2012 y desde 2021, L1 de 2022 a 2025</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f2_metrobus.png" class="img-fluid figure-img"></p>
<figcaption>F2 · Metrobús: 53,732 filas, 14 valores de línea y 17,227 <code>'NaN'</code></figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f3_gtfs.png" class="img-fluid figure-img"></p>
<figcaption>F3 · GTFS: 195 paradas del Metro de 11,362 en total</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f4_festivos.png" class="img-fluid figure-img"></p>
<figcaption>F4 · festivos desplazados respecto a la LFT (p.&nbsp;ej. 2010-04-30, 2016-05-02)</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/PERF_f5_clima.png" class="img-fluid figure-img"></p>
<figcaption>F5 · clima: 6,056 días, de 2010-01-01 a 2026-07-31</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="análisis-de-integración" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-integración">1.5 Análisis de integración</h2>
<section id="llaves-de-unión" class="level3">
<h3 class="anchored" data-anchor-id="llaves-de-unión">Llaves de unión</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Llave</th>
<th>F1 Metro</th>
<th>F2 Metrobús</th>
<th>F3 GTFS</th>
<th>F4 Festivos</th>
<th>F5 Clima</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Fecha</strong></td>
<td><code>fecha</code> (texto ISO)</td>
<td><code>fecha</code> (texto ISO)</td>
<td>— (catálogo estático)</td>
<td><code>date</code> (ISO)</td>
<td><code>time</code> (ISO, hora local)</td>
</tr>
<tr class="even">
<td><strong>Línea</strong></td>
<td><code>linea</code>: <code>Linea 1</code> / <code>LÃ­nea 1</code></td>
<td><code>linea</code>: <code>Línea 1</code> / <code>linea 1</code></td>
<td><code>route_short_name</code> + <code>agency_id</code></td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td><strong>Estación</strong></td>
<td><code>linea</code> + <code>estacion</code> (texto)</td>
<td>—</td>
<td><code>stop_id</code>, <code>stop_name</code></td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>La fecha une las cinco fuentes sin conversión de zona horaria, porque F5 se pide en <code>America/Mexico_City</code>. La línea se normaliza a un código (<code>1</code>…<code>12</code>, <code>A</code>, <code>B</code>) que conforma <code>dim_linea</code> para los dos sistemas.</p>
<p><strong>Prueba de unión estación ↔︎ GTFS.</strong> Probamos la unión de F1 con F3 tomando el 2026-07-31. Primero corregimos la doble codificación y luego normalizamos acentos y mayúsculas. Con eso, <strong>187 de 195 estaciones (95.9 %) coinciden exactamente</strong> con una parada de F3 en la misma línea. Las 8 restantes son nombres compuestos que cada fuente escribe distinto:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 47%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Línea</th>
<th>F1 (afluencia)</th>
<th>F3 (GTFS)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>Zócalo/Tenochtitlan</td>
<td>Zócalo</td>
</tr>
<tr class="even">
<td>3</td>
<td>Etiopía/Plaza de la Transparencia</td>
<td>Etiopía y Plaza de la Transparencia</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Niños Héroes</td>
<td>Niños Héroes y Poder Judicial CDMX</td>
</tr>
<tr class="even">
<td>3</td>
<td>Viveros/Derechos Humanos</td>
<td>Viveros y Derechos Humanos</td>
</tr>
<tr class="odd">
<td>6</td>
<td>Ferrería/Arena Ciudad de México</td>
<td>Ferrería y Arena Ciudad de México</td>
</tr>
<tr class="even">
<td>6</td>
<td>La Villa/Basílica</td>
<td>La Villa y Basílica</td>
</tr>
<tr class="odd">
<td>8</td>
<td>Garibaldi/Lagunilla</td>
<td>Garibaldi y Lagunilla</td>
</tr>
<tr class="even">
<td>B</td>
<td>Garibaldi/Lagunilla</td>
<td>Garibaldi y Lagunilla</td>
</tr>
</tbody>
</table>
<p>Se resolverán con una <strong>tabla de equivalencias de 8 filas</strong> en E2. El conteo por línea coincide: F1 y F3 tienen las mismas estaciones por línea (L1: 20, L2: 24, L3: 21, L4: 10, L5: 13, L6: 11, L7: 14, L8: 19, L9: 12, L12: 20, A: 10, B: 21).</p>
</section>
<section id="diferencias-de-granularidad" class="level3">
<h3 class="anchored" data-anchor-id="diferencias-de-granularidad">Diferencias de granularidad</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 35%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Fuente</th>
<th>Grano nativo</th>
<th>Cómo entra al DW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1</td>
<td>estación-línea × día</td>
<td>Directo al hecho principal</td>
</tr>
<tr class="even">
<td>F2</td>
<td>línea × día</td>
<td>Segundo hecho, con <code>dim_fecha</code> y <code>dim_linea</code> conformadas</td>
</tr>
<tr class="odd">
<td>F3</td>
<td>parada (sin tiempo)</td>
<td>Atributos de <code>dim_estacion</code> y <code>dim_linea</code></td>
</tr>
<tr class="even">
<td>F4</td>
<td>evento (solo días festivos)</td>
<td>Atributos de <code>dim_fecha</code>; los demás días quedan como no festivos</td>
</tr>
<tr class="odd">
<td>F5</td>
<td>día, un punto para toda la ciudad</td>
<td><code>dim_clima</code>, un registro por día</td>
</tr>
</tbody>
</table>
</section>
<section id="problemas-anticipados-se-documentan-se-resuelven-en-e2" class="level3">
<h3 class="anchored" data-anchor-id="problemas-anticipados-se-documentan-se-resuelven-en-e2">Problemas anticipados (se documentan, se resuelven en E2)</h3>
<ol type="1">
<li><strong>Doble codificación UTF-8/Latin-1</strong> en <code>linea</code> y <code>estacion</code> de F1. Se repara antes de normalizar, porque si no se repara una misma estación genera dos llaves.</li>
<li><strong>Nombres compuestos</strong> (8 estaciones). Ninguna fuente conserva la historia de nombres: F3 es una foto de la red a octubre de 2022 y F1 reescribe el nombre actual hacia atrás (<em>Zócalo/Tenochtitlan</em> aparece desde 2010-01-01). Por eso el nombre se trata como atributo sin historia y la SCD tipo 2 de <code>dim_estacion</code> se reserva para el estado de servicio.</li>
<li><strong>Ceros estructurales frente a ceros operativos.</strong> Un cero puede ser una línea no inaugurada, un cierre largo o un cierre de un día. Los cierres largos se modelan como estado de servicio en <code>dim_estacion</code>. Los de un día quedan marcados con <code>es_registro_cero</code> en el hecho.</li>
<li><strong><code>'NaN'</code> como texto en F2.</strong> Se convierte a <code>NULL</code>, no a cero, porque no significa “nadie viajó” sino “la línea no existía”.</li>
<li><strong>Festivos desplazados en F4.</strong> Nager.Date mueve el Día del Trabajo cuando cae en fin de semana (2010-04-30, 2011-05-02, 2016-05-02, 2021-04-30, 2022-05-02) y hace lo mismo con el Año Nuevo (2010-12-31, 2012-01-02, 2017-01-02, 2021-12-31, 2023-01-02). La Ley Federal del Trabajo (art. 74) no prevé ese desplazamiento, así que el festivo se valida contra la ley y se usa la fecha legal.</li>
<li><strong>Clima de un solo punto.</strong> F5 representa toda la ciudad con una celda de malla, y una tormenta local no aparece. Es una limitación para P4 que se declara en la <a href="../../entregas/E1_arquitectura_dw/trazabilidad.html">matriz de trazabilidad</a>.</li>
<li><strong>GTFS desactualizado.</strong> F3 corresponde a la versión del 31 de octubre de 2022. El Metro no ha abierto estaciones desde 2012, así que la lista de 195 sigue completa, pero un cambio de nombre posterior a esa fecha no aparecería en F3. Por eso la tabla de equivalencias se revisa contra F1, que sí es reciente.</li>
<li><strong>Actualizaciones retroactivas</strong> en F1 y F2 (riesgo R2) y reanálisis en F5. Cada carga a staging registra su fecha de descarga.</li>
</ol>
</section>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<ul>
<li>SEMOVI. <em>Afluencia diaria del Metro CDMX</em>. Portal de Datos Abiertos de la CDMX. <a href="https://datos.cdmx.gob.mx/dataset/afluencia-diaria-del-metro-cdmx" class="uri">https://datos.cdmx.gob.mx/dataset/afluencia-diaria-del-metro-cdmx</a></li>
<li>SEMOVI. <em>Afluencia diaria de Metrobús CDMX</em>. <a href="https://datos.cdmx.gob.mx/dataset/afluencia-diaria-de-metrobus-cdmx" class="uri">https://datos.cdmx.gob.mx/dataset/afluencia-diaria-de-metrobus-cdmx</a></li>
<li>SEMOVI. <em>GTFS estático de la Ciudad de México</em>. <a href="https://datos.cdmx.gob.mx/dataset/gtfs" class="uri">https://datos.cdmx.gob.mx/dataset/gtfs</a></li>
<li>Nager.Date. <em>Public Holidays API</em>. <a href="https://date.nager.at" class="uri">https://date.nager.at</a> · repositorio: <a href="https://github.com/nager/Nager.Date" class="uri">https://github.com/nager/Nager.Date</a></li>
<li>Open-Meteo. <em>Historical Weather API</em> y licencia. <a href="https://open-meteo.com/en/licence" class="uri">https://open-meteo.com/en/licence</a></li>
<li>INEGI. <em>Estadística de Transporte Urbano de Pasajeros (ETUP)</em>. <a href="https://www.inegi.org.mx/rnm/index.php/catalog/741" class="uri">https://www.inegi.org.mx/rnm/index.php/catalog/741</a></li>
<li>Ley Federal del Trabajo, art. 74 (días de descanso obligatorio).</li>
</ul>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Volver arriba</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/fernando-bm\.github\.io\/Proyecto_Mineria_Datos");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../entregas/E0_comprension_negocio/fuentes.html" class="pagination-link" aria-label="7. Fuentes consultadas">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">7. Fuentes consultadas</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../entregas/E1_arquitectura_dw/arquitectura.html" class="pagination-link" aria-label="2. Arquitectura de tres capas en BigQuery">
        <span class="nav-page-text">2. Arquitectura de tres capas en BigQuery</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Facultad de Ciencias, UNAM · Almacenes y Minería de Datos</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Datos: SEMOVI, Portal de Datos Abiertos de la CDMX (CC-BY-4.0-ESP)</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>